
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "uat" ]
  pull_request:
    branches: [ "uat" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains a single job called "deploy"
jobs:
  deployment:
     # The type of runner that the job will run on
   runs-on: ubuntu-latest
   environment: production
   steps:
      - name: deploy
      - uses: actions/checkout@v3
     
      #install salesforce cli           
      - name: 'Install Salesforce CLI'
        run: |
           npm install sfdx-cli
           node_modules/sfdx-cli/bin/run --version
           node_modules/sfdx-cli/bin/run plugins --core
      
      # Store secret for dev hub
      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
        shell: bash
        run: |
            echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
            secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
            if [ $secretFileSize == 1 ]; then
                  echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
                  exit 1;
            fi
        # Authenticate dev hub
      - name: 'Authenticate Dev Hub'
        run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
      
      - name: 'test case'
        run: sfdx force:apex:test:run 
      
         # Merge to uat      
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'  
